# Generated by Django 4.2 on 2023-04-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.CharField(default='non-exist', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='id_notice',
            field=models.TextField(default='non-exist'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='non-exist'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
